### PR TITLE
Update it_IT.lang + more Subsets localization

### PR DESCRIPTION
**Pull request by TheVikingWarrior**
I added the nei subsets localization for Fluids, i tried to do the same with the line:
nei.subsets.Items.FluidContainers=Fluid Containers
But it didn't work when i tried to translate it.

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
I don't think the Fluids subset is me, maybe Waila or NEI Plugins?

**Comment by TheVikingWarrior** [comment]
ok, i'll try to find it

**Comment by Chicken-Bones** [comment]
also, subset localisations can have spaces, so try 
nei.subsets.Items.Fluid Containers=Fluid Containers

**Comment by TheVikingWarrior** [comment]
Yeah, it's nei plugins, i'll ad the translation there

**Pull request closed without merging**
