### PR TITLE
Fix crash when loading world in Dev-Workspace

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Just a little change, which should fix it :D

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
Have you matched the mcp mappings versions? https://github.com/Chicken-Bones/NotEnoughItems/blob/master/build/build.gradle#L52

**Comment by ThexXTURBOXx** [comment]
Should match.
I didn't test it on my PC yet, but I think, that it works

**Comment by Chicken-Bones** [comment]
The reason I ask is that it's likely you are using a different version of the mappings in your dev workspace to what NEI is compiled with on the repo, if I was to just add your change, it's very likely that NEI would fail to build.

**Comment by ThexXTURBOXx** [comment]
Ok, I will look again and then just comment again, if it matches

**Comment by ThexXTURBOXx** [comment]
export.mcpbot.bspk.rs/mcp_snapshot_nodoc/20150404-1.8/mcp_snapshot_nodoc-20150404-1.8.zip
Yeah, it matches and should fix the issue

**Pull request closed without merging**
